<b style="font-size: 3rem">Bueautiful Soup and Requests</b>

<b style="font-size: 2rem">Scrape This Site Web Scraper </b>

In [15]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [16]:
base_url = "https://www.scrapethissite.com/pages/forms/"

page = requests.get(base_url)

soup = BeautifulSoup(page.text, "html")

In [17]:
# soup.prettify() # Prettify() is added just to beautifies the response

<b style="font-size: 2rem">Find and Find_all || FindAll</b>

In [18]:
# soup.find_all("p", class_ ="lead")

In [19]:
# soup.find("p", class_ ="lead").text.strip()

In [20]:
# soup.find("table") # soup.find("table", class_ = "table") # If there are more than one table, you can use class or id to get your target

In [21]:
table_columns = soup.find_all("th")
# table_columns

In [22]:
# Looping through the heading row and print each field

for column in table_columns:
    print(column.text.strip())

Team Name
Year
Wins
Losses
OT Losses
Win %
Goals For (GF)
Goals Against (GA)
+ / -

In [23]:
# Creating a list of column titles

table_columns = [column.text.strip() for column in table_columns]
print(table_columns)

['Team Name', 'Year', 'Wins', 'Losses', 'OT Losses', 'Win %', 'Goals For (GF)', 'Goals Against (GA)', '+ / -']

In [24]:
# First page table data

table_data = soup.find_all("td")
table_data_list = [row.text.strip() for row in table_data]

In [25]:
# Table rows converted to list

num_columns = 9
table_rows = [table_data_list[i:i + num_columns] for i in range(0, len(table_data_list), num_columns)]

# table_rows

In [26]:
# Creating a dataframe of the scraped page

df = pd.DataFrame(table_rows, columns=table_columns)
df

,Team Name,Year,Wins,Losses,OT Losses,Win %,Goals For (GF),Goals Against (GA),+ / -
0,Boston Bruins,1990,44,24,,0.55,299,264,35
1,Buffalo Sabres,1990,31,30,,0.388,292,278,14
2,Calgary Flames,1990,46,26,,0.575,344,263,81
3,Chicago Blackhawks,1990,49,23,,0.613,284,211,73
4,Detroit Red Wings,1990,34,38,,0.425,273,298,-25
5,Edmonton Oilers,1990,37,37,,0.463,272,272,0
6,Hartford Whalers,1990,31,38,,0.388,238,276,-38
7,Los Angeles Kings,1990,46,24,,0.575,340,254,86
8,Minnesota North Stars,1990,27,39,,0.338,256,266,-10
9,Montreal Canadiens,1990,39,30,,0.487,273,249,24
10,New Jersey Devils,1990,32,33,,0.4,272,264,8
11,New York Islanders,1990,25,45,,0.312,223,290,-67
12,New York Rangers,1990,36,31,,0.45,297,265,32
13,Philadelphia Flyers,1990,33,37,,0.412,252,267,-15
14,Pittsburgh Penguins,1990,41,33,,0.512,342,305,37
15,Quebec Nordiques,1990,16,50,,0.2,236,354,-118
16,St. Louis Blues,1990,47,22,,0.588,310,250,60
17,Toronto Maple Leafs,1990,23,46,,0.287,241,318,-77
18,Vancouver Canucks,1990,28,43,,0.35,243,315,-72
19,Washington Capitals,1990,37,36,,0.463,258,258,0
20,Winnipeg Jets,1990,26,43,,0.325,260,288,-28
21,Boston Bruins,1991,36,32,,0.45,270,275,-5
22,Buffalo Sabres,1991,31,37,,0.388,289,299,-10
23,Calgary Flames,1991,31,37,,0.388,296,305,-9
24,Chicago Blackhawks,1991,36,29,,0.45,257,236,21

<b style="font-size: 1.5rem">Scraping all the pages data at once</b>

In [27]:
# Define the base URL and the total number of pages  
base_url = 'https://www.scrapethissite.com/pages/forms/?page_num='  
total_pages = 24  

def scrape_page(page_num):  
    # Send an HTTP request to the page  
    response = requests.get(base_url + str(page_num))  
    
    # Check if the request was successful  
    if response.status_code != 200:  
        print(f"Failed to retrieve data from page {page_num}")  
        return []  
    
    # Parse the HTML content  
    soup = BeautifulSoup(response.content, 'html')  
    
    # Find the table and extract rows    
    table_rows = soup.select('table tr')  
    
    data_list = []  
    
    # Loop through the rows, skipping the header  
    for row in table_rows[1:]:  
        columns = row.find_all('td')  
        if columns:  
            # Scrap each relevant data point  
            data = [col.get_text(strip=True) for col in columns]  
            data_list.append(data)  

    return data_list  

# List to hold data from all pages  
all_data = []  

# Loop through all the pages and collect data  
for page in range(1, total_pages + 1):  
    # print(f"Scraping page {page}...")  
    page_data = scrape_page(page)  
    all_data.extend(page_data)  

# Convert the collected data into a DataFrame   
df_all = pd.DataFrame(all_data, columns=table_columns)  

# Save the DataFrame to a CSV file  
df_all.to_csv('hockey_stats.csv', index=False)  

# Display the final DataFrame  
df_all

,Team Name,Year,Wins,Losses,OT Losses,Win %,Goals For (GF),Goals Against (GA),+ / -
0,Boston Bruins,1990,44,24,,0.55,299,264,35
1,Buffalo Sabres,1990,31,30,,0.388,292,278,14
2,Calgary Flames,1990,46,26,,0.575,344,263,81
3,Chicago Blackhawks,1990,49,23,,0.613,284,211,73
4,Detroit Red Wings,1990,34,38,,0.425,273,298,-25
...,...,...,...,...,...,...,...,...,...
577,Tampa Bay Lightning,2011,38,36,8,0.463,235,281,-46
578,Toronto Maple Leafs,2011,35,37,10,0.427,231,264,-33
579,Vancouver Canucks,2011,51,22,9,0.622,249,198,51
580,Washington Capitals,2011,42,32,8,0.512,222,230,-8
581,Winnipeg Jets,2011,37,35,10,0.451,225,246,-21